services:
  jeopardy-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: feelings-jeopardy-app
    container_name: jeopardy-game
    ports:
      - "9081:80"
    restart: unless-stopped
